modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="trumpetskeleton"
version="${file.jarVersion}"
displayName="Trumpet Skeleton"

authors="JamiesWhiteShirt (port by gdude2002)"

description='''
The sound of trumpets echoes through the night...
'''

[[dependencies.trumpetskeleton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
